ScrumGuides/ScrumGuide-ExpansionPack

- site/content/guide/index.md
- site/layouts/download/list.html
This pull request introduces enhancements to improve user experience and analytics tracking on the site. The most significant changes include adding a sitemap priority for better SEO and implementing Google Analytics event tracking for PDF downloads.
* [`site/content/guide/index.md`](diffhunk://#diff-7fd1291b77709f98daddec06ec56ef46d68075515e8c5f3daea204901abb2093R20-R22): Added a `sitemap` section with a priority of `1.0` to improve the page's discoverability by search engines.
* [`site/layouts/download/list.html`](diffhunk://#diff-61a17293eed6d2aa243bbb04f3b4ec17ef30bdcb65012ace839fb11f16a111f0L68-R74): Added `onclick` handlers to track PDF download events with Google Analytics. These handlers capture details such as event category, language, file name, and file extension for official …
> Post release technical changes

- .github/ISSUE_TEMPLATE/new-translation.yml
🌐 i18n(issue-template): add pre-submission checklist for translations
- Introduce a pre-submission checklist to ensure language is not duplicated
- require confirmation that the language is not already proposed or in progress
> Update Translation Form

- docs/translations.md
The intent of this guide is to help folks understand how to translate the content.
Review: https://github.com/ScrumGuides/ScrumGuide-ExpansionPack/blob/create-translation-guide/docs/translations.md
---
👋 To review this PR, go to the **Files changed** tab, leave comments on any lines you'd like to discuss, and then use the **Review changes** button (top right) to either **Approve**, **Request changes**, or just **Comment**.
Full GitHub guide: [[Reviewing changes in pull requests](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests)](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests)
> Create translation Guide

- .github/workflows/main.yaml
- add ref to checkout action to ensure correct commit is used in pull request builds
- improve reliability of workflow by fetching specific pull request head sha
> 👷 ci(workflows): enhance checkout action for pull requests

- .github/workflows/main.yaml
- add PR number, URL, title, branch, and commit information to workflow
- include fork status to improve workflow context and traceability
> 👷 ci(workflows): enhance GitHub actions with PR metadata

- .github/ISSUE_TEMPLATE/new-translation.yml
- change label from "enhancement" to "triage" for better categorization
📝 docs(templates): enhance translation request instructions
- add clarification to prevent duplicate translation efforts
- ensure a smooth translation process for contributors
> 🔧 chore(templates): update translation issue template labels

- .github/ISSUE_TEMPLATE/translation-error.yml
- .github/copilot-instructions.md
- site/i18n/en.yaml
- site/i18n/tlh.yaml
- site/layouts/guide/single.html
✨ feat(layout): add translation error reporting link
- introduce a "Report Translation Error" button for non-English content
- enhance user feedback for translation issues via GitHub link
> Add Report Translation Error Button

- .github/copilot-instructions.md
- .github/workflows/copilot-setup-steps.yml
- Add detailed setup instructions for development environment
- Introduce new sections for testing, configuration, and troubleshooting
- Enhance content guidelines with multilingual and UX testing details
👷 ci(workflow): add copilot setup steps workflow
- Create a new GitHub Actions workflow for copilot setup
- Automate Hugo installation and repository checkout
- Include environment verification steps for CI process
> 📝 docs(guide): expand copilot instructions

- .github/ISSUE_TEMPLATE/translation-error.yml
- .github/workflows/discussion-tag-external-edits.yml
🌐 i18n(issue-template): update translation language options
- add English and Farsi to language options in issue template
👷 ci(workflow): add workflow to tag external edits
- create workflow to label discussions edited by external contributors
- check organization membership and collaborator status for contributors
- add 'creator_review_required' label if contributor is external
> Make new discussion more transparent to creators

- site/content/guide/index.fa.md
- site/layouts/translations/list.html
- include Pooya Sabramooz as a contributor in the Farsi guide
💄 style(translations): improve HTML and JavaScript code formatting
- adjust indentation for better readability
- ensure consistent use of quotes in JavaScript
- remove unnecessary whitespace and line breaks
> 🌐 i18n(guide): add contributor information to Farsi guide

- site/content/guide/index.md
He wasn't added after we had received his ok email on June 12.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ScrumGuides/ScrumGuide-ExpansionPack/97)
> Added Tom Mellor to contributors 

- .github/workflows/docs-to-wiki.yml
- change shell to PowerShell for listing changed files
- update action version for github-docs-to-wiki to v0.20
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ScrumGuides/ScrumGuide-ExpansionPack/102)
> 👷 ci(workflow): update docs-to-wiki workflow for Windows compatibility

- site/hugo.yaml
- add a status parameter with value "reference" to the Klingon language settings for enhanced configuration options
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ScrumGuides/ScrumGuide-ExpansionPack/129)
> 🌐 i18n(locale): add status parameter to Klingon language settings

- site/layouts/_partials/functions/get-translations.html
♻️ refactor(translations): optimize translation data loading
- consolidate loading of production and preview language data
- streamline URL determination based on environment
- improve language filtering logic for clarity and efficiency
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ScrumGuides/ScrumGuide-ExpansionPack/132)
> Try to load languages live

- site/hugo.yaml
- site/layouts/_partials/functions/get-translations.html
- remove duplicate status entry in Klingon language configuration
- differentiate local and remote file loading based on environment for production and preview settings
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ScrumGuides/ScrumGuide-ExpansionPack/133)
> ♻️ refactor(i18n): streamline translation loading logic

- site/content/guide/index.es.md
- add contributor information for Alex Ballarin as translator
- include LinkedIn link and GitHub username for transparency
💄 style(guide): adjust formatting for consistency
- ensure consistent use of italics and underscores
- fix spacing issues and remove unnecessary whitespace
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ScrumGuides/ScrumGuide-ExpansionPack/150)
> 🌐 i18n(guide): update Spanish guide with translator information

- site/content/guide/index.es.md
- change title and description for better clarity and consistency
- update dates and keywords for accuracy
- refine various sections for improved readability and translation consistency
- adjust terminology for better alignment with Scrum framework concepts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ScrumGuides/ScrumGuide-ExpansionPack/172)
> 🌐 i18n(guide): update Spanish translations in Scrum guide

- site/content/scrum-guide-expansion-pack/2025.6/Multi-Team-Scrum.md
this is a clone of the whole document which will be slimmed down for the multi team content
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ScrumGuides/ScrumGuide-ExpansionPack/218)
> Initial upload of Multi-Team-Scrum file

- site/content/scrum-guide-expansion-pack/2025.6/References.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ScrumGuides/ScrumGuide-ExpansionPack/220)
> Initial upload of references raw file

- site/content/scrum-guide-expansion-pack/2025.6/Adaptive Organization.md
updated title
updated section
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ScrumGuides/ScrumGuide-ExpansionPack/225)
> Adaptive Organization upload

- site/content/scrum-guide-expansion-pack/2025.6/Complexity.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ScrumGuides/ScrumGuide-ExpansionPack/227)
> Initial upload

- site/content/scrum-guide-expansion-pack/2025.6/Scrum Expanded.md
removed Multi Team section as it has its own document
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ScrumGuides/ScrumGuide-ExpansionPack/235)
> Update Scrum Expanded.md

- site/content/scrum-guide-expanded/2025.9/index.md
- Changed formatting of deviations from SG2020 from code snippets to underlined text for better
readability
- Added more detailed explanations of formatting conventions
- Added impact references to augment outcome descriptions where helpful
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ScrumGuides/ScrumGuide-ExpansionPack/253)
> Improved formatting for SG2020 changes and added Impact more prominently
